openapi: 3.0.2
info:
  title:
    Images Api
  description:
    ImageResize API to get data from DynamoDB
  version: 1.0.0
paths:
  /:
    get:
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        200:
          description: "OK"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json: {}
      x-amazon-apigateway-integration:
        description: get all images in the database
        credentials:  { 'Fn::GetAtt': APIRole.Arn }
        uri: { 'Fn::Sub': 'arn:aws:apigateway:${AWS::Region}:dynamodb:action/Scan' }
        requestTemplates:
          application/json:
            Fn::Sub:
              - |-
                {
                  "TableName": "${tableName}"
                }
              - { tableName: { Ref: imageDynamoDBTable } }
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: '#set($inputRoot = $input.path("$"))
                          {
                            "pics": [
                              #foreach($elem in $inputRoot.Items) 
                                "$elem.Image.S"
                              #if($foreach.hasNext),#end
                              #end
                            ]
                          }'
        passthroughBehavior: 'when_no_match'
        httpMethod: POST
        type: AWS

